name: Run CSM tests
on:
  push:

jobs:
  ubuntu_tests:
    runs-on: ubuntu-latest
    name: Run CSM tests on Ubuntu
    strategy:
      matrix:
        python-version: [ '3.7' , '3.8', '3.9', '3.10' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Open Babel
        run: |
          Invoke-WebRequest https://github.com/openbabel/openbabel/releases/download/openbabel-3-1-1/OpenBabel-3.1.1-x64.exe -OutFile OpenBabel-3.1.1-x64.exe
          OpenBabel-3.1.1-x64.exe 
      - name: Build CSM
        working-directory: src
        run: |
          pip install wheel
          pip install -r requirements.txt
          pip install pytest
          python setup.py prepare
          python setup.py build_ext
          shopt -s globstar
          cp build/**/fast*.so csm
      - name: Run tests
        working-directory: src
        run: |
          export PYTHONPATH="."
          pytest tests

  # We do not run tests on Windows because we couldn't figure out how to install OpenBabel through a Github Worklow
  # The OpenBabel installer doesn't seem to have a quiet mode.
