name: Create CSM Wheels
on:
  push:
    tags:
      - v*

jobs:
  # manylinux-wheels:
  #   runs-on: ubuntu-latest
  #   name: Create the manylinux wheels for all supported Python versions
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Build docker image
  #       working-directory: src
  #       run: docker build -f Dockerfile.manylinux . -t csm-manylinux:latest --build-arg GITHUB_VERSION=${{ github.ref }}
  #     - name: Copy wheels
  #       working-directory: src
  #       run: |
  #         docker run --rm --name csm-manylinux -v `pwd`:/external csm-manylinux:latest
  #     - name: Upload to Release
  #       id: upload-release-asset
  #       uses: svenstaro/upload-release-action@v2
  #       with:
  #         repo_token: ${{ secrets.GITHUB_TOKEN }}
  #         file: src/csm-wheels/csm*.whl
  #         file_glob: true
  #         tag: ${{ github.ref }}
  #         overwrite: true
  #         body: "Linux Wheels"

  # windows-wheels:
  #   runs-on: windows-latest
  #   strategy:
  #     matrix:
  #       python-version: [ '3.7', '3.8', '3.9', '3.10' ]
  #   name: Create the Windows Wheel for Python ${{ matrix.python-version }}
  #   env:
  #     GITHUB_VERSION: ${{ github.ref }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Setup Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #         architecture: x64
  #     - name: Set Python environment
  #       working-directory: src
  #       run: |
  #         python ./install_requirements.py
  #         pip install wheel
  #     - name: Create the wheel
  #       working-directory: src
  #       run: |
  #         python setup.py prepare
  #         pip wheel .
  #     - name: Upload to Release
  #       id: upload-release-asset
  #       uses: svenstaro/upload-release-action@v2
  #       with:
  #         repo_token: ${{ secrets.GITHUB_TOKEN }}
  #         file: src/csm*.whl
  #         file_glob: true
  #         tag: ${{ github.ref }}
  #         overwrite: true
  #         body: "Windows Wheels"
  
  # source-package:
  #   runs-on: windows-latest
  #   name: Create the Windows Wheel for Python ${{ matrix.python-version }}
  #   env:
  #     GITHUB_VERSION: ${{ github.ref }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Setup Python
  #       uses: actions/setup-python@v2
  #       with:
  #         architecture: x64
  #     - name: Set Python environment
  #       working-directory: src
  #       run: |
  #         python ./install_requirements.py
  #         pip install wheel
  #     - name: Create the wheel
  #       working-directory: src
  #       run: |
  #         python setup.py prepare
  #         python setup.py sdist
  #     - name: Upload to Release
  #       id: upload-release-asset
  #       uses: svenstaro/upload-release-action@v2
  #       with:
  #         repo_token: ${{ secrets.GITHUB_TOKEN }}
  #         file: src/dist/csm*.tar.gz
  #         file_glob: true
  #         tag: ${{ github.ref }}
  #         overwrite: true
  #         body: "Source Package"
      
  build-docker-image:
    #needs: manylinux-wheels
    runs-on: ubuntu-latest
    name: Create the docker image using wheels
    steps:
      - name: Set env
        #run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        #run: echo "RELEASE_VERSION_NUM=${GITHUB_REF#*v}"" >> $GITHUB_ENV
        
        run: |
          echo "REF=refs/tags/v1.3.0b32" >> $GITHUB_ENV
          echo "RELEASE_VERSION='${REF##*/}' >> $GITHUB_ENV
          echo "RELEASE_VERSION_NUM='${REF##*v}' >> $GITHUB_ENV
          echo "WHL_NAME='csm-'$RELEASE_VERSION_NUM'-cp39-cp39-manylinux_2_24_x86_64.whl'" >> $GITHUB_ENV 
          echo "Variables:"
          echo $REF
          echo $RELEASE_VERSION
          echo $RELEASE_VERSION_NUM
          echo $WHL_NAME

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: $RELEASE_VERSION
      
      - name: get wheels
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'continuous-symmetry-measure/csm'
          version: tags/$RELEASE_VERSION
          file: $WHL_NAME
          target: src/$WHL_NAME
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        working-directory: src
        run: docker build . --tag $RELEASE_VERSION --build-arg WHL=$WHL_NAME --build-arg CSM_VER=$RELEASE_VERSION